      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.232.122.214 << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd ~/techstory-weaver
            git remote set-url origin git@github.com:thelaststock/techstory-weaver.git
            git pull origin main
            pnpm install
            pnpm build
            pm2 restart techstory-weaver
          EOF
