name: Deploying techstory-weaver (frontend)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts

      - name: Install Node & Build
        run: |
          corepack enable
          pnpm install
          pnpm build

      - name: Upload build to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" dist/ ubuntu@13.232.122.214:/home/ubuntu/techstory-weaver-frontend/
