name: Deploying techstory-weaver-ui
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy and Build on Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.200.161.40 << 'EOF'
            set -e  # stop on error

            # Go to project directory
            cd ~/techstory-weaver

            # Pull latest changes
            git pull origin main

            # Load Node (optional if using nvm)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Install dependencies and build
            corepack enable
            pnpm install
            pnpm build

            # Set permissions
            sudo chown -R www-data:www-data dist
            sudo chmod -R 755 dist

            # Reload Nginx if needed
            sudo systemctl reload nginx
          EOF
